# Generated by Django 3.2.16 on 2023-10-14 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formulaireevenement',
            old_name='nom',
            new_name='nom_insta',
        ),
        migrations.RemoveField(
            model_name='formulaireevenement',
            name='mur_flora',
        ),
        migrations.RemoveField(
            model_name='formulaireevenement',
            name='reseaux',
        ),
        migrations.AddField(
            model_name='formulaireevenement',
            name='mur_floral',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='formulaireevenement',
            name='genre',
            field=models.CharField(choices=[('F', 'Féminin'), ('M', 'Masculin')], max_length=1),
        ),
        migrations.AlterField(
            model_name='formulaireevenement',
            name='jour_semaine',
            field=models.CharField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi'), ('Dimanche', 'Dimanche')], max_length=10),
        ),
        migrations.AlterField(
            model_name='formulaireevenement',
            name='ok',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], max_length=3),
        ),
        migrations.AlterField(
            model_name='formulaireevenement',
            name='origine',
            field=models.CharField(choices=[('Indien', 'Indien'), ('Sri', 'Sri'), ('Europe', 'Europe'), ('Afrique', 'Afrique'), ('Arab', 'Arab'), ('Chinois', 'Chinois'), ('Portugais', 'Portugais'), ('Russe', 'Russe'), ('Turque', 'Turque'), ('Juifs', 'Juifs')], max_length=10),
        ),
        migrations.AlterField(
            model_name='formulaireevenement',
            name='photobooth',
            field=models.CharField(choices=[('photobooth', 'Photobooth'), ('miroirbooth', 'Miroirbooth'), ('360booth', '360booth')], max_length=12),
        ),
        migrations.AlterField(
            model_name='formulaireevenement',
            name='prix_propose',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='formulaireevenement',
            name='type_mariage',
            field=models.CharField(choices=[('Mariage', 'Mariage'), ('Anniversaire Maison', 'Anniversaire Maison'), ('Anniversaire Salle', 'Anniversaire Salle')], max_length=20),
        ),
    ]
