# Generated by Django 3.2.16 on 2023-10-14 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20231015_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulaireevenement',
            name='ok',
            field=models.BooleanField(default=False),
        ),
    ]
