# Generated by Django 3.2.16 on 2023-10-14 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_formulaireevenement_ok'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulaireevenement',
            name='photobooth',
            field=models.CharField(choices=[('photobooth', 'Photobooth'), ('miroirbooth', 'Miroirbooth'), ('360booth', '360booth'), ('miroirbooth+360booth', 'miroirbooth+360booth')], max_length=100),
        ),
    ]
