# Generated by Django 3.2.16 on 2023-10-14 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_formulaireevenement_photobooth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulaireevenement',
            name='origine',
            field=models.CharField(choices=[('Indien-Sri', 'Indien-Sri'), ('Europe', 'Europe'), ('Afrique', 'Afrique'), ('Arab', 'Arab'), ('Chinois', 'Chinois'), ('Portugais', 'Portugais'), ('Russe', 'Russe'), ('Turque', 'Turque'), ('Juifs', 'Juifs')], max_length=10),
        ),
    ]
