# Generated by Django 3.2.16 on 2023-10-14 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_formulaireevenement_origine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulaireevenement',
            name='commentaire',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='formulaireevenement',
            name='date_event',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='formulaireevenement',
            name='photobooth',
            field=models.CharField(choices=[('photobooth', 'Photobooth'), ('miroirbooth', 'Miroirbooth'), ('360booth', '360booth'), ('miroirbooth+360booth', 'miroirbooth+360booth')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formulaireevenement',
            name='prix_propose',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='formulaireevenement',
            name='salle',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formulaireevenement',
            name='type_mariage',
            field=models.CharField(choices=[('Mariage', 'Mariage'), ('Anniversaire Maison', 'Anniversaire Maison'), ('Anniversaire Salle', 'Anniversaire Salle')], max_length=20, null=True),
        ),
    ]
