# Generated by Django 3.2.16 on 2023-10-14 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20231015_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulaireevenement',
            name='salle',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
