# Generated by Django 3.2.16 on 2023-10-16 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_formulaireevenement_relance'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulaireevenement',
            name='chezconcurrent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='formulaireevenement',
            name='salle',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
