# Generated by Django 3.2.16 on 2023-10-16 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20231017_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulaireevenement',
            name='jour_semaine',
        ),
    ]
