# Generated by Django 3.2.16 on 2023-11-12 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_formulaireevenement_jour_semaine'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulaireevenement',
            name='pas_de_dispo',
            field=models.BooleanField(default=False),
        ),
    ]
