# Generated by Django 3.2.16 on 2023-11-13 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_formulaireevenement_pas_de_dispo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulaireevenement',
            name='date_event',
            field=models.DateField(blank=True, null=True),
        ),
    ]
