# Generated by Django 3.2.16 on 2023-11-13 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_formulaireevenement_date_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulaireevenement',
            name='prix_propose',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formulaireevenement',
            name='type_mariage',
            field=models.CharField(choices=[('je sais pas', 'je sais pas'), ('Mariage', 'Mariage'), ('Anniversaire Maison', 'Anniversaire Maison'), ('Anniversaire Salle', 'Anniversaire Salle')], max_length=100, null=True),
        ),
    ]
